# Remove UART, console output, and boot banners for current measurement.
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_PM_DEVICE=n
CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
